### ISSUE TITLE
"keys.h" is lost

### ISSUE THREAD

**Issue by 73begonia** [edoardo911/DXR-Path-Tracer#4]

**Comment by 73begonia** [comment]
and cannot open file 'nvsdk_ngx_d_dbg.lib'

**Comment by edoardo911** [comment]
The file `src/utils/keys.h` is not included because it contains all (one at the moment of writing this) private keys used by the engine.
It defines an `inline const char projectKey[38]` inside engine namespace initialized following the NVIDIA DLSS' guidelines: 
> Project ID is assumed to be GUID-like, for instance: "a0f57b54-1daf-4934-90ae-c4035c19df04"
https://github.com/NVIDIA/DLSS/blob/main/doc/DLSS_Programming_Guide_Release.pdf

The missing .lib files have been added with the latest commit (`292718a`)

**Comment by kawaii-desune** [comment]
> The file `src/utils/keys.h` is not included because it contains all (one at the moment of writing this) private keys used by the engine. It defines an `inline const char projectKey[38]` inside engine namespace initialized following the NVIDIA DLSS' guidelines:
> 
> > Project ID is assumed to be GUID-like, for instance: "a0f57b54-1daf-4934-90ae-c4035c19df04"
> > https://github.com/NVIDIA/DLSS/blob/main/doc/DLSS_Programming_Guide_Release.pdf
> 
> The missing .lib files have been added with the latest commit (`292718a`)

Hi, when I compile the program, NRD.dll is missing, I have problem when I compile NRT_SDK library, can you upload the missing .dll pls. Thx

**Comment by edoardo911** [comment]
They've been added with the latest commit

**Comment by JiaqiJin** [comment]
> They've been added with the latest commit

Thx you so much :)

**Comment by kawaii-desune** [comment]
> They've been added with the latest commit

Thx you so much :)
